services:
  eureka-server:
    image: ofentselekgetho/safety_encrypt:eureka-server-v1
    container_name: eureka-server
    ports:
      - 8761:8761

  crypto-service:
    image: ofentselekgetho/safety_encrypt:crypto_service-v4
    container_name: crypto-service
    ports:
      - 8100:8100

  api-gateway:
    image: ofentselekgetho/safety_encrypt:api-gateway-v3
    container_name: api-gateway
    ports:
      - 8080:8080
